# -- mode: ruby --
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "Web2" do |web|

      web.vm.hostname = "Web2"
      web.vm.box = "chavinje/fr-bull-64"
      web.vm.network :public_network, bridge: "eno1", use_dhcp_assigned_default_route: true

    web.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--name", "Web2"]
      v.customize ["modifyvm", :id, "--cpus", "1"]
      v.customize ["modifyvm", :id, "--memory", 2*1024]
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
    end
    config.vm.provision "shell", inline: <<-SHELL
      sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config    
      sleep 3
      service ssh restart
    SHELL
    web.vm.provision "shell", path: "scripts/install_sys.sh"
    web.vm.provision "shell", path: "scripts/install_web.sh"
    web.vm.provision "shell", path: "scripts/install_nrpe_web.sh"
    web.vm.provision "shell", path: "scripts/install_wazuh_agent.sh"
  end
end
